import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'palette-pally',
  description: 'Generated by create next app',
  // icons: {
  //   icon: '/favicon.ico',
  //   shortcut: '/favicon.ico',
  //   apple: '/apple-touch-icon.png',
  // },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body className="max-w-screen-2xl mx-auto">{children}</body>      
    </html>
  )
}
